---
- name: Install HAProxy
  ansible.builtin.apt:
    pkg: haproxy
    state: present

- name: Create haproxy config
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg

- name: Disable OS haproxy service
  ansible.builtin.service:
    name: haproxy
    enabled: yes
    state: restarted
  