---
- name: Get flux_0.22.0_linux_amd64.tar.gz
  ansible.builtin.get_url:
    url: https://github.com/fluxcd/flux2/releases/download/v0.23.0/flux_0.23.0_linux_amd64.tar.gz
    dest: /tmp
    mode: '0440'
    checksum: sha256:aadb219ccf89c1da3d32ed534affdd815003a7aada241883621fc945925a2d56

- name: Extract flux_0.23.0_linux_amd64.tar.gz into /usr/local/bin
  ansible.builtin.unarchive:
    src: /tmp/flux_0.23.0_linux_amd64.tar.gz
    dest: /usr/local/bin
    creates: /usr/local/bin/flux
    remote_src: yes

- name: Save github known-host
  ansible.builtin.shell: ssh-keyscan -4 -T 5 -t rsa github.com 2>&1 > "/home/{{ ansible_user }}/.ssh/flux_known_hosts"
  args:
    creates: "/home/{{ ansible_user }}/.ssh/flux_known_hosts"

- name: Save github id_rsa
  ansible.builtin.copy:
    content: "{{ github_code_ssh_key }}"
    dest: "/home/{{ ansible_user }}/.ssh/flux_github_id_rsa"

# until I figure out how to answer the question in script :(
# - name: Setup flux
#   ansible.builtin.shell: flux bootstrap git --components-extra=image-reflector-controller,image-automation-controller --url=ssh://git@github.com/scottasmith/git-ops.git --branch=master --path=clusters/homecluster --private-key-file="/home/{{ ansible_user }}/.ssh/glux_githuub_id_rsa"
#
##
#   flux bootstrap git --components-extra=image-reflector-controller,image-automation-controller --url=ssh://git@github.com/scottasmith/git-ops.git --branch=master --path=clusters/homecluster --private-key-file="/home/ansible/.ssh/flux_github_id_rsa"
##
#
#   environment:
#     SSH_KNOWN_HOSTS: "/home/{{ ansible_user }}/.ssh/flux_known_hosts"
