---
- name: Install calico
  become: false
  ansible.builtin.shell: kubectl create -f https://docs.projectcalico.org/manifests/tigera-operator.yaml >> calico_setup.log
  args:
    chdir: "/home/{{ ansible_user }}"
    creates: calico_setup.log

- name: Create calico installation yaml
  ansible.builtin.copy:
    src: calico/calico-installation.yaml
    dest: "/home/{{ ansible_user }}/calico-installation.yaml"

- name: Calico installation
  become: false
  ansible.builtin.shell: kubectl apply -f calico-installation.yaml >> calico_install.log
  args:
    chdir: "/home/{{ ansible_user }}"
    creates: calico_install.log

- name: Create calico etc directory
  ansible.builtin.file:
    path: /etc/calico
    state: directory

- name: Create calico bgp configuration file
  ansible.builtin.copy:
    src: calico/calicoctl.cfg
    dest: /etc/calico/calicoctl.cfg

- name: Install calico binary
  ansible.builtin.shell: >
    wget https://github.com/projectcalico/calicoctl/releases/download/v3.14.0/calicoctl 1> /dev/null 2> /dev/null &&
    chmod +x calicoctl &&
    mv calicoctl /usr/local/bin
  args:
    creates: /usr/local/bin/calicoctl

- name: Create calico bgp configuration file
  ansible.builtin.template:
    src: calico-bgpconfiguration.yaml.j2
    dest: "/home/{{ ansible_user }}/calico-bgpconfiguration.yaml"

- name: Configure calico for bgp peering
  ansible.builtin.shell: "calicoctl apply -f /home/{{ ansible_user }}/calico-bgpconfiguration.yaml"

# Probably should find a better home for this :)
- name: Create configmap for ingresscontroller
  ansible.builtin.shell: kubectl create configmap haproxy-kubernetes-ingress --dry-run=client  -o yaml | kubectl apply -f -
