# persistent data location
root = "/var/lib/containerd"

# runtime state information
state = "/run/containerd"

# set containerd's OOM score
oom_score = -999

[grpc]
  address = "/run/containerd/containerd.sock"

[metrics]
  address = "127.0.0.1:1338"

# Kubernetes runs best when we are using the same cgroup root
# https://kubernetes.io/docs/setup/production-environment/container-runtimes/
#
# Temporarily disabled as on Debian 11 - https://github.com/kubernetes/kubernetes/issues/106464
#
#[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
#  SystemdCgroup = true