---
- name: Generate join token
  ansible.builtin.shell: kubeadm token create --print-join-command
  register: kubeadm_join_cmd_raw
  delegate_to: "{{ groups['k8s_control_plane'][0] }}"
  changed_when: false

- name: set k8 join command as fact
  ansible.builtin.set_fact:
    kubeadm_join_cmd: "{{ kubeadm_join_cmd_raw.stdout }}"
  when: kubeadm_join_cmd is not defined

- name: Show join command
  ansible.builtin.debug:
    msg: "{{ kubeadm_join_cmd }}"

- name: Execute join command
  ansible.builtin.shell: "{{ kubeadm_join_cmd }} >> cluster_init.log"
  args:
    chdir: "/home/{{ ansible_user }}"
    creates: "/home/{{ ansible_user }}/cluster_init.log"
