---
- hosts: kubernetescluster:kubernetesproxy
  become: true
  gather_facts: false

  roles:
    - hostfile

- hosts: kubernetescluster
  become: true
  gather_facts: true

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

  roles:
    - containerd
    - kubernetes

- hosts: k8-master-1
  become: true
  gather_facts: true

  tasks:
    - name: Initialise Kubernetes master
      include_role:
        name: kubernetes
        tasks_from: init_master

    - name: Initialise Kubernetes network
      include_role:
        name: kubernetes
        tasks_from: init_network

    # This should be in the GitOps repo
    # - name: Setup Kubernetes certificate signer
    #   include_role:
    #     name: kubernetes
    #     tasks_from: init_certificate_signing

- hosts: k8-worker-*
  become: true
  gather_facts: true

  tasks:
    - name: Initialise Kubernetes workers
      include_role:
        name: kubernetes
        tasks_from: init_workers

- hosts: k8-master-1,kubernetesproxy
  become: true
  gather_facts: true

  tasks:
    - name: Get Kubernetes config
      ansible.builtin.shell: cat /etc/kubernetes/admin.conf
      register: kubernetes_config_raw
      changed_when: false
      when: inventory_hostname == 'k8-master-1'

    - name: Set Kubernetes join command as fact
      ansible.builtin.set_fact:
        kubernetes_config: "{{ kubernetes_config_raw.stdout }}"
      when: inventory_hostname == 'k8-master-1'

    - name: initialise proxy server
      include_role:
        name: kubernetes
        tasks_from: init_proxy
      when: inventory_hostname != 'k8-master-1'

- hosts: k8-master-1
  become: true
  gather_facts: false

  tasks:
    - name: initialise kadalu
      include_role:
        name: kubernetes
        tasks_from: init_kadalu

    - name: initialise fluxci
      include_role:
        name: kubernetes
        tasks_from: init_flux

- hosts: k8-master-1,kubernetesproxy
  become: true
  gather_facts: true

  roles:      
    - keepalived