---
- hosts: all
  become: true
  gather_facts: true
  roles:
  - hostfile

# Initialise the whole cluster (lb's including so we can utilise BGP/etc.)
- hosts: k8s_cluster
  become: true
  gather_facts: true
  roles:
  - containerd
  - k8s-requirements

# Initial setup of the cluster if not already set up.
- hosts: k8-master-1
  become: true
  gather_facts: true
  roles:
  - k8s-control-plane

# Setup rest of the masters
- hosts: k8s_control_plane:!k8-master-1
  become: true
  gather_facts: true
  roles:
  - k8s-control-plane

# Setup normal worker nodes 
- hosts: k8s_workers
  become: true
  gather_facts: true
  roles:
  - k8s-workers

# Setup loadbalancers and services
- hosts: k8-master-1
  become: true
  gather_facts: true
  roles:
  - k8s-network
  - k8s-services

# Setup loadbalancers and services
- hosts: k8_lbs
  become: true
  gather_facts: true
  tasks:
  - name: Add haproxy node label
    ansible.builtin.shell: kubectl label nodes "{{ inventory_hostname }}" node-role=haproxy-ingress
    delegate_to: "{{ groups['k8s_control_plane'][0] }}"
