- hosts: k8s_cluster:k8-master-1
  become: true
  gather_facts: true

  tasks:
    - name: Insert a line at the end of /var/lib/kubelet/config.yaml
      lineinfile:
        path: /var/lib/kubelet/config.yaml
        line: 'serverTLSBootstrap: true'
    - name: restart kubelet
      shell: systemctl restart kubelet