---
kubernetes_pkg_version: 1.22.4-00
kubernetes_version: v1.22.4

kubernetes_api_vip: "192.168.2.20"
kubernetes_api_vip_cidr: "192.168.2.20/24"
kubernetes_api_vip_port: 443

kubernetes_api_port: 6443

kubernetes_pod_subnet: "10.244.0.0/16"

kubernetes_calico_bgp_asn: 65000

kubernetes_csr_resources: ["scottsmith.me.uk/*"]

kadalu_pools:
- name: "pool1"
  volume_id: "381fed44-cedd-11eb-8344-666bff195b24"
  type: "Replica3"